## Acessando elementos dentro da matrix

In [3]:
import numpy as np

In [ ]:
# Criando um vetor com a biblioteca numpy
arr = np.array([1,2,3,4,5])

In [ ]:
# Acessando elementos dentro do vetor
print(arr[0])

1


In [ ]:
# Criando outro vetor com a biblioteca numpy
arr = np.array([[6, 3], [0, 2]])

In [ ]:
# Acessando elementos dentro do vetor
print(arr[0])

[6 3]


## Fatiamento

In [ ]:
# Criando a matriz com a bilioteca numpy
arr = np.array([1,2,3,4,5])

In [ ]:
# Imprimindo a parte fatiada do vetor
print(repr(arr[:]))

array([1, 2, 3, 4, 5])


In [ ]:
# Imprimindo a parte fatiada do vetor
print(repr(arr[1:]))

array([2, 3, 4, 5])


In [ ]:
# Imprimindo a parte fatiada do vetor
print(repr(arr[2:4]))

array([3, 4])


In [ ]:
# Imprimindo a parte fatiada do vetor
print(repr(arr[:-1]))

array([1, 2, 3, 4])


In [ ]:
# Imprimindo a parte fatiada do vetor
print(repr(arr[-2:]))

array([4, 5])


In [ ]:
# Criando uma matriz com a biblioteca numpy
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [ ]:
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


## Comandos Argmin and argmax

In [4]:
# Criando uma matriz 
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])

In [7]:
print(np.argmin(arr[0]))
print(np.argmax(arr[1]))
print(np.argmin(arr))

2
1
5


In [8]:
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


## Let`s Code! 


Set elem equal to the third element of the second row in data (remember that the first row is index 0). Then return elem.

In [9]:
def direct_index(data):
  elem = data[1][2]
  return elem

In [10]:
def slice_data(data):
  slice1 = data[:, 1:]
  slice2 = data[0:3, :-2]
  return slice1, slice2

In [11]:
def argmin_data(data):
  argmin_all = np.argmin(data)
  argmin1 = np.argmin(data, axis=1)
  return argmin_all, argmin1

In [12]:
def argmax_data(data):
  argmax_neg1 = np.argmax(data, axis=-1)
  return argmax_neg1