In [2]:
import numpy as np

## Aritmética básica

In [4]:
# Criando uma matriz
arr = np.array([[1, 2], [3, 4]])
print("Matriz: ", repr(arr))

Matriz:  array([[1, 2],
       [3, 4]])


In [5]:
# Somando um para cada elemento na matriz
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [6]:
# Subtraindo -1.2 de cada elemento na matriz
print(repr(arr - 1.2))

array([[-0.2,  0.8],
       [ 1.8,  2.8]])


In [7]:
# Dobrando cada elemento da matriz
print(repr(arr * 2))

array([[2, 4],
       [6, 8]])


In [8]:
# Divindo cada elemento da matriz
print(repr(arr / 2))

array([[0.5, 1. ],
       [1.5, 2. ]])


In [9]:
# Valor inteiro para cada elemento na matriz
print(repr(arr // 2))

array([[0, 1],
       [1, 2]])


In [10]:
# Elevando cada elemento da matriz ao quadrado
print(repr(arr**2))

array([[ 1,  4],
       [ 9, 16]])


In [11]:
# Raiz quadrada de cada elemento da matriz
print(repr(arr**0.5))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


Convertendo Fahrenheit para Celsius

In [14]:
# Definindo uma função para converter os valores de Fahrenheit para Celsius
def f2c(temps):
  return (5/9)*(temps-32)

# Criando uma matriz com valores em Fahrenheits
fahrenheits = np.array([32, -4, 14, -40])
print("Fahrenheits: ", repr(fahrenheits))
celsius = f2c(fahrenheits)

# Imprimindo um valor em Celsius:
print('Celsius: {}'.format(repr(celsius)))

Fahrenheits:  array([ 32,  -4,  14, -40])
Celsius: array([  0., -20., -10., -40.])


# Non-Linear functions

In [18]:
# Criando a matriz do tipo inteiro (32 bits)
arr = np.array([[1,2],[3,4]], dtype=np.int32)
print('Array: ', repr(arr))

Array:  array([[1, 2],
       [3, 4]], dtype=int32)


In [19]:
# Elevando cada elemento contido na matriz a potência e
exp = np.exp(arr)
print("Matriz final: ", exp)

Matriz final:  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [21]:
# Elevando cada elemento contido na matri a potencia 2
exp2 = np.exp2(arr)
print("Matriz final: ", exp2)

Matriz final:  [[ 2.  4.]
 [ 8. 16.]]


In [26]:
# Criando uma matriz utilizando a biblioteca numpy para geração dos valores de euler e pi
arr2 = np.array([[1,10],[np.e, np.pi]])
print('Matriz: ', arr2)

Matriz:  [[ 1.         10.        ]
 [ 2.71828183  3.14159265]]


In [ ]:
arr = 