In [2]:
import numpy as np

## Aritmética básica

In [ ]:
# Criando uma matriz
arr = np.array([[1, 2], [3, 4]])
print("Matriz: ", repr(arr))

Matriz:  array([[1, 2],
       [3, 4]])


In [ ]:
# Somando um para cada elemento na matriz
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [ ]:
# Subtraindo -1.2 de cada elemento na matriz
print(repr(arr - 1.2))

array([[-0.2,  0.8],
       [ 1.8,  2.8]])


In [ ]:
# Dobrando cada elemento da matriz
print(repr(arr * 2))

array([[2, 4],
       [6, 8]])


In [ ]:
# Divindo cada elemento da matriz
print(repr(arr / 2))

array([[0.5, 1. ],
       [1.5, 2. ]])


In [ ]:
# Valor inteiro para cada elemento na matriz
print(repr(arr // 2))

array([[0, 1],
       [1, 2]])


In [ ]:
# Elevando cada elemento da matriz ao quadrado
print(repr(arr**2))

array([[ 1,  4],
       [ 9, 16]])


In [ ]:
# Raiz quadrada de cada elemento da matriz
print(repr(arr**0.5))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


Convertendo Fahrenheit para Celsius

In [ ]:
# Definindo uma função para converter os valores de Fahrenheit para Celsius
def f2c(temps):
  return (5/9)*(temps-32)

# Criando uma matriz com valores em Fahrenheits
fahrenheits = np.array([32, -4, 14, -40])
print("Fahrenheits: ", repr(fahrenheits))
celsius = f2c(fahrenheits)

# Imprimindo um valor em Celsius:
print('Celsius: {}'.format(repr(celsius)))

Fahrenheits:  array([ 32,  -4,  14, -40])
Celsius: array([  0., -20., -10., -40.])


# Non-Linear functions

In [ ]:
# Criando a matriz do tipo inteiro (32 bits)
arr = np.array([[1,2],[3,4]], dtype=np.int32)
print('Array: ', repr(arr))

Array:  array([[1, 2],
       [3, 4]], dtype=int32)


In [ ]:
# Elevando cada elemento contido na matriz a potência e
exp = np.exp(arr)
print("Matriz final: ", exp)

Matriz final:  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [ ]:
# Elevando cada elemento contido na matri a potencia 2
exp2 = np.exp2(arr)
print("Matriz final: ", exp2)

Matriz final:  [[ 2.  4.]
 [ 8. 16.]]


In [ ]:
# Criando uma matriz utilizando a biblioteca numpy para geração dos valores de euler e pi
arr2 = np.array([[1,10],[np.e, np.pi]])
print('Matriz: ', arr2)

Matriz:  [[ 1.         10.        ]
 [ 2.71828183  3.14159265]]


In [11]:
# Usando Logaritmo
print(repr(np.log(arr2)))
print(repr(np.log10(arr2)))

array([[2.32238772, 1.38629436],
       [1.09861229, 1.60943791]])
array([[1.00860017, 0.60205999],
       [0.47712125, 0.69897   ]])


In [4]:
# Criando uma matriz 
arr = np.array([[1, 2], [3, 4]])
print(repr(arr))

array([[1, 2],
       [3, 4]])


In [5]:
# Elevando a matriz a potência 3
print(repr(np.power(3, arr)))

array([[ 3,  9],
       [27, 81]])


In [10]:
# Elevando cada elemento de uma matriz pelo elemento de outra matriz
arr2 = np.array([[10.2, 4], [3, 5]])
print('Matriz 1: ', repr(arr))
print('Matriz 2: ', repr(arr2))
print('Resultado: ', np.power(arr, arr2))


Matriz 1:  array([[1, 2],
       [3, 4]])
Matriz 2:  array([[10.2,  4. ],
       [ 3. ,  5. ]])
Resultado:  [[1.000e+00 1.600e+01]
 [2.700e+01 1.024e+03]]


# Exercícios

Exercício

In [13]:
# Criando a primeira matriz
arr = np.array([[-0.5, 0.8, -0.1], 
                [0.0, -1.2, 1.3]])

# Criando a segunda matriz
arr2 = np.array([[1.2, 3.1], 
                 [1.2, 0.3],
                 [1.5, 2.2]])

Exercício 2

In [15]:
# Efetuando a multiplicação de cada elemento da matriz por pi
multiplied = arr * np.pi
print(repr(arr))

array([[-0.5,  0.8, -0.1],
       [ 0. , -1.2,  1.3]])


In [17]:
# Efeuando a soma de matrizes
added = arr + multiplied
print(repr(added))

array([[-2.07079633,  3.31327412, -0.41415927],
       [ 0.        , -4.96991118,  5.38407045]])


In [23]:
# Elevando cada elemento da matriz ao quadrado
squared = np.power(added, 2)
print(repr(squared))

array([[ 4.28819743, 10.97778541,  0.1715279 ],
       [ 0.        , 24.70001718, 28.98821461]])


Exercício 3

In [24]:
exponential = np.exp(squared)
print(repr(exponential))

array([[7.28350596e+01, 5.85587272e+04, 1.18711726e+00],
       [1.00000000e+00, 5.33434578e+10, 3.88527393e+12]])


In [25]:
logged = np.log(arr2)
print(repr(arr2))

array([[1.2, 3.1],
       [1.2, 0.3],
       [1.5, 2.2]])


Exercício 4

In [32]:
# Efetuando a multiplicacao de matrizes
matmul1 = np.matmul(logged, exponential)
print(repr(matmul1))

array([[ 1.44108036e+01,  6.03529115e+10,  4.39580713e+12],
       [ 1.20754286e+01, -6.42240618e+10, -4.67776415e+12],
       [ 3.03205327e+01,  4.20590657e+10,  3.06337283e+12]])


In [33]:
# Efetuando a multiplicacao de matrizes 2
matmul2 = np.matmul(exponential, logged)
print(repr(matmul2))

array([[ 1.06902790e+04, -7.04197733e+04],
       [ 1.58506868e+12,  2.99914875e+12]])
