In [ ]:
# Importando a biblioteca numpy
import numpy as np

# Random integers

In [ ]:
# Gerar diversos valores aleatorios
print('Valor 1: ', np.random.randint(10))
print('Valor 2: ', np.random.randint(10))
print('Valor 3: ', np.random.randint(10, high=20))

Valor 1:  8
Valor 2:  6
Valor 3:  19


In [ ]:
# Gerando uma matriz aleatoria
random_arr = np.random.randint(-3, high=14, size=(2, 2))
print(repr(random_arr))

array([[ 2, -1],
       [ 9,  8]])


# Funções utilitárias

In [ ]:
# Gerar uma semente
np.random.seed(1)

In [ ]:
# Gerar um valor aleatorio
print(np.random.randint(10))

5


In [ ]:
# Gerar uma matriz aleatorio
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

array([[12, 78],
       [ 8, 82]])


In [ ]:
# Gerar uma semente
np.random.seed(2)

In [ ]:
# Gerar um valor aleatorio
print(np.random.randint(10))

8


In [ ]:
# Gerar uma matriz aleatorio
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

array([[18, 75],
       [25, 46]])


In [ ]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [ ]:
# Criando um vetor
vec = np.array([1, 2, 3, 4, 5])
print(repr(vec))

array([1, 2, 3, 4, 5])


In [ ]:
# Mudando a ordem aleatoriamente dos elementos do vetor (1)
np.random.shuffle(vec)
print(repr(vec))

array([3, 4, 2, 5, 1])


In [ ]:
# Mudando a ordem aleatoriamente dos elementos do vetor (2)
np.random.shuffle(vec)
print(repr(vec))

array([2, 5, 3, 4, 1])


In [ ]:
# Gerando uma matriz
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Aleatorizando os indices dos elementos da matriz
np.random.shuffle(matrix)
print(repr(matrix))

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])


# Distribuição

In [24]:
# Distribuição Uniforme
print(np.random.uniform())
print(np.random.uniform(low=1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=3.4, high=5.9,
                             size=(2,2))))

0.44345289377955666
1.660704049610878
array([0.53441391, 0.91396202, 0.45720481])
array([[4.47674642, 5.74781947],
       [5.34597309, 5.18992629]])


In [25]:
# Distribuição Normal
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=2.4, scale=4.0,
                            size=(2, 2))))

1.118296977299658
1.6946461648546718
array([[3.90662654, 3.90454009],
       [1.74323692, 2.06182621]])


# Custom sampling

In [27]:
# Gerando uma lista de cores
colors = ['red', 'blue', 'green']

# Escolhando aleatoriamente uma cor
print(np.random.choice(colors))

print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01])))

red
array(['green', 'green'], dtype='<U5')
array([['blue', 'red'],
       ['red', 'red']], dtype='<U5')


# Exercícios


Exercício 1

In [30]:
# Gerando um valor aleatorio
random1 = np.random.randint(5)
print(repr(random1))

3


In [31]:
# Gerando uma matriz de elementos aleatoria
random_arr = np.random.randint(3, high=10, size=(3, 5))
print(repr(random_arr))

array([[9, 8, 7, 6, 8],
       [4, 6, 9, 3, 3],
       [5, 5, 4, 6, 7]])


Exercício 2

In [34]:
# Gerando uma matriz de valores seguindo uma distribuição normal
random_norm = np.random.normal(loc=2.0, scale=3.5, size=(10,5))
print(repr(random_norm))

array([[ 4.80651361,  2.16298554,  1.3470058 ,  1.64388945,  5.04110155],
       [ 4.62644074,  3.85312864,  2.48195423,  2.27237395,  4.16433092],
       [ 2.81373096,  4.38892992,  0.91459129, -6.52193217,  5.63588611],
       [ 9.65442876,  3.54477555,  1.64945668,  1.5224434 ,  1.58331034],
       [ 2.06093293, -1.92706555,  0.1901694 , -1.4895939 ,  2.87079706],
       [ 0.96175597,  3.73323963,  1.38853894,  5.45217316,  2.74736865],
       [ 9.66744905, -4.63726323, -0.26420841,  5.15520412, 10.84913997],
       [ 1.12977828,  2.15284148,  1.20790015,  6.66009989,  0.99442248],
       [ 4.38024444,  0.8806944 , -2.45395564,  3.09741702,  3.76114685],
       [ 6.52629059,  1.61343541, -0.16076722,  3.96966384,  2.84257982]])


Exercício 3

In [36]:
choices = ['a', 'b', 'c', 'd']
choice = np.random.choice(choices, p=[0.5, 0.1, 0.2, 0.2])

Exercício 4

In [48]:
# Gerando o vetor
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr))

array([1, 2, 3, 4, 5])


In [49]:
# Aleatorizando os elementos dos vetores
np.random.shuffle(arr)