In [1]:
# Importando a biblioteca
import numpy as np

## Summation

In [7]:
# Criando a matriz
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

In [8]:
# Imprimindo a soma dos elementos da matriz
print(np.sum(arr))

18


In [10]:
# Imprimindo a soma dos elementos no eixo 0
print(repr(np.sum(arr, axis = 0)))

array([ -2,  73, -53])


In [11]:
# Imprimindo a soma dos elementos no eixo 1 
print(repr(np.sum(arr, axis = 1)))

array([ 75, -56,  -1])


In [13]:
# Imprimindo a soma acomulada dos elementos da matriz
print(repr(np.cumsum(arr)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])


In [16]:
# Imprimindo a soma acomulada dos elementos da matriz no eixo 0
print(repr(np.cumsum(arr, axis=0)))

array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])


In [15]:
# Imprimindo a soma acomulada dos elementos da matriz no eixo 1
print(repr(np.cumsum(arr, axis=1)))

array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


## Concatenation

In [17]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])

In [18]:
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])

In [19]:
# Imprimundo a concatenação das duas matrizes
print(repr(np.concatenate([arr1, arr2])))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])


In [21]:
# Imprimindo a concatenação das duas matrizes no eixo 0
print(repr(np.concatenate([arr1, arr2], axis=0)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])


In [22]:
# Imprimindo a concatenação das duas matrizes no eixo 0
print(repr(np.concatenate([arr1, arr2], axis=1)))

array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])


## Time to code

In [23]:
def get_sums(data):
  total_sum = np.sum(data)
  col_sum = np.sum(data, axis=0)
  return total_sum, col_sum

In [ ]:
def get_cumsum(data):
  row_cumsum = np.cumsum(data, axis=1)
  return row_cumsum

In [24]:
def concat_arrays(data1, data2):
  col_concat = np.concatenate([data1, data2], axis=0)
  row_concat = np.concatenate([data1, data2], axis=1)
  return col_concat, row_concat