In [ ]:
# Importando a biblioteca Numpy
import numpy as np

## Filtering data

In [ ]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])

In [ ]:
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])


In [ ]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])

In [ ]:
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


## Filtering in Numpy

In [ ]:
print(repr(np.where([True, False, True])))

# (array([0, 2]),)
# Os valores TRUE estão nos índices 0 e 2

(array([0, 2]),)


In [ ]:
arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

# (array([1, 3]),)
# Os valores que satisfazem estão nos índices 1 e 3

(array([1, 3]),)


In [ ]:
arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])

In [ ]:
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


In [ ]:
# Gerando os vetores
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])

In [ ]:
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])


In [ ]:
np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

array([[-2, -5],
       [ 3,  4]])


In [ ]:
np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[-2, -5],
       [-1, -8]])


In [ ]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
print(repr(np.where(np_filter, positives, -1)))

array([[ 1, -1],
       [-1,  4]])


## Axis-wise filtering

In [ ]:
# Gerando a matriz
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])

In [ ]:
print(repr(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])


In [ ]:
print(np.any(arr > 0))

True


In [ ]:
print(np.all(arr > 0))

False


In [ ]:
print(repr(np.any(arr > 0, axis=0)))

array([ True,  True,  True])


In [ ]:
print(repr(np.any(arr > 0, axis=1)))

array([False,  True,  True])


In [ ]:
print(repr(np.all(arr > 0, axis=1)))

array([False, False,  True])


In [ ]:
has_positive = np.any(arr > 0, axis=1)

In [ ]:
print(has_positive)

[False  True  True]


In [ ]:
print(repr(arr[np.where(has_positive)]))

array([[ 4,  5, -6],
       [ 3,  9,  1]])


## Time to code

Set a tuple of x_ind, y_ind equal to the output of np.where, applied with the condition data > 0.

Then return data[x_ind, y_ind].

In [ ]:
def get_positives(data):
  x_ind, y_ind = np.where(data >0)
  return data[x_ind, y_ind]

In [ ]:
def replace_zeros(data):
  zeros = np.zeros_like(data)
  zero_replace = np.where(data > 0, data, zeros)
  return zero_replace

In [1]:
def replace_neg_one(data):
  neg_one_replace = np.where(data > 0, data, -1)
  return neg_one_replace

In [2]:
def coin_flip_filter(data):
  coin_flips = np.random.randint(2, size=data.shape)
  bool_coin_flips = coin_flips.astype(np.bool)
  one_replace = np.where(bool_coin_flips, data, 1)
  return one_replace