## Matrizes e tipos

In [1]:
# Importando as bibliotecas necessárias
import numpy as np

In [2]:
# Uma simples matriz de valores inteiros
arr = np.array([[0,1,2], 
                [3,4,5]],
               dtype=np.float32)

In [4]:
# Imprimindo os valores contidos da matriz
print(arr)

[[0. 1. 2.]
 [3. 4. 5.]]


In [5]:
# Uma simples matrix com valores reais e inteiros
arr = np.array([0, 0.1, 2])

In [6]:
# Imprimindo os valores contidos na matriz
print(repr(arr))

array([0. , 0.1, 2. ])


Todos os valores agora são do tipo "float" 

## Copiando valores entre matrizes

In [9]:
# Criando os vetores A e B
vector_a = np.array([0, 1])
vector_b = np.array([9, 8])

In [10]:
# Copiando os valores de A para um novo vetor C
vector_c = vector_a

In [11]:
# Imprimindo os valores contidos nos vetores:
print('Vetor A: ', vector_a)
print('Vetor C: ', vector_c)

Vetor A:  [0 1]
Vetor C:  [0 1]


In [13]:
# Alterando o valor no índice 0 do vetor C:
vector_c[0] = 5

In [14]:
# Imprimindo os valores contidos nos vetores:
print('Vetor A: ', vector_a)
print('Vetor C: ', vector_c)

Vetor A:  [5 1]
Vetor C:  [5 1]


O pacote Numpy de modo análogo as listas em Python não criam uma nova matriz com os comandos apresentados logo acima. Portanto, qualquer modificação feita no vector_a irá refletir no vector_c e vice-versa.

In [15]:
# Copiando os valores de A para um novo vetor DÇ
vector_d = vector_a.copy()

In [16]:
# Imprimindo os valores contidos nos vetores:
print('Vetor A: ', vector_a)
print('Vetor D: ', vector_d)

Vetor A:  [5 1]
Vetor D:  [5 1]


In [17]:
# Alterando o valor no índice 0 do vetor D:
vector_d[0] = 0

In [18]:
# Imprimindo os valores contidos nos vetores:
print('Vetor A: ', vector_a)
print('Vetor D: ', vector_d)

Vetor A:  [5 1]
Vetor C:  [0 1]


Quando utilizamos a função "copy()" conseguimos criar uma nova matriz com os valores contidos em outra matriz.

## Fundir

In [19]:
# Criando um novo vetor
arr = np.array([0, 1, 2])

In [20]:
# Imprimindo o tipo do vetor
print(arr.dtype)

int64


In [21]:
# Alterando o tipo do vetor
arr = arr.astype(np.float32)

In [23]:
# Imprimindo o tipo do vetor
print(arr.dtype)

float32


## Not a Number (NaN) value

In [25]:
# Criando um vetor com NaN values
arr = np.array([np.nan, 1, 2])

# Imprimindo os valores contidos na matriz
print(repr(arr))

array([nan,  1.,  2.])


In [32]:
arr = np.array([np.nan, 'abc'])
print(repr(arr))

array(['nan', 'abc'], dtype='<U32')


In [31]:
np.array([np.nan, 1, 2], dtype=np.float32)

array([nan,  1.,  2.], dtype=float32)

## Infinito

In [33]:
# Imprimindo um valor muito alto
print(np.inf > 1000000)

True


In [35]:
# Criando um vetor com valor +infinito
arr = np.array([np.inf, 5])

# Imprimindo os valores contidos no vetor
print(repr(arr))

array([inf,  5.])


In [36]:
# Criando um vetor com valor -infinito
arr = np.array([-np.inf, 1])

# Imprimindo os valores contidos no vetor
print(repr(arr))

array([-inf,   1.])


## Exercícios

Exercício 1

In [37]:
# Criando o vetor com os valores propostos: 
arr = np.array([np.nan, 2, 3, 4, 5])

Exercício 2

In [40]:
# Copiano o vetor 
arr2 = arr.copy()
arr2[0] = 10

Exercício 3 

In [45]:
# Criando o primeiro vetor do tipo float 
float_arr = np.array([1, 5.4, 3])

# Criando o segundo vetor do tipo inteiro para conversão
float_arr2 = np.array([1, 5.4, 3], np.int32)

# Convertendo o segundo vetor para o tipo float32
float_arr2 = arr2.astype(np.float32)

Exercício 4

In [46]:
# Criando a matriz 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]],
                  dtype=np.float32)