In [ ]:
import numpy as np

## Ranged data

Criando um vetor com a função 'range' da biblioteca numpy


In [ ]:
arr = np.arange(5) #  '5' é a quantidade de valores em um intervalo de 0 à 5
print(repr(arr))

array([0, 1, 2, 3, 4])


In [ ]:
arr = np.arange(5.1) # '5' é quantidade de valores, porém agora em String
print(repr(arr))

array([0., 1., 2., 3., 4., 5.])


In [ ]:
arr = np.arange(-1, 4) # Inserindo dois argumentos é possível mudar o intervalor de valores gerados
print(repr(arr))

array([-1,  0,  1,  2,  3])


In [ ]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

array([ 5.,  7.,  9., 11.])


In [ ]:
arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

array([5. , 6.5, 8. , 9.5])


In [ ]:
arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([5, 6, 8, 9], dtype=int32)


## Reshape

In [ ]:
arr = np.arange(8)
print(repr(arr))

array([0, 1, 2, 3, 4, 5, 6, 7])


In [ ]:
reshaped_arr = np.reshape(arr, (2, 4)) # Transformando o vetor em uma matriz
print(repr(reshaped_arr))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])


In [ ]:
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])


In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (2,4))  # Tranforma o vetor em matriz 2x4
flattened = arr.flatten() # Transforma a matriz 2x4 em um vetor
print('Reshaped array: ',  arr)
print('Flattened array: ', flattened)

Reshaped array:  [[0 1 2 3]
 [4 5 6 7]]
Flattened array:  [0 1 2 3 4 5 6 7]


## Transposing

In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
transposed = np.transpose(arr)
print('Array: ', repr(arr))
print('Transposed array: ', repr(transposed)) 

Array:  array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
Transposed array:  array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])


In [ ]:
arr = np.arange(24)
arr = np.reshape(arr, (3,4,2))
transposed = np.transpose(arr, axes=(1,2,0))
print('Array: ', repr(arr))
print('Transposed: ', repr(transposed))

Array:  array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])
Transposed:  array([[[ 0,  8, 16],
        [ 1,  9, 17]],

       [[ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21]],

       [[ 6, 14, 22],
        [ 7, 15, 23]]])


## Zeros and ones

In [29]:
arr = np.array([[1 ,2],
               [3, 4]])
print('Array: ', repr(arr))

Array:  array([[1, 2],
       [3, 4]])


In [30]:
arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))

array([[1., 1.],
       [1., 1.]])


## Exercícios

#### Exercício 1

In [32]:
# Desenvolvendo o vetor
arr = np.arange(12)
print(repr(arr))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [33]:
# Transformando o vetor em matriz
reshaped = np.reshape(arr, (2, 3, 2))
print(repr(reshaped))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])


#### Exercício 2

In [40]:
# Fazendo a tranposta do vetor
transposed = np.transpose(reshaped, axes=(1, 2, 0))
print('Transposed: ', repr(transposed))

Transposed:  array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])


In [35]:
# Transformando a matriz em vetor
flattened = reshaped.flatten()
print('Flattened: ', flattened)

Flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
# Fazendo a tranposta da matriz
transposed = np.transpose(reshaped, axes = (1, 2, 0))
print('Transposed: ', repr(transposed))

Transposed:  array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])


#### Exercício 3

In [47]:
# Criando um vetor de zeros
zeros_arr = np.zeros(5)
print('Vetor de zeros: ', repr(zeros_arr))

Vetor de zeros:  array([0, 0, 0, 0, 0], dtype=int32)


In [51]:
# Criando um vetor de uns
ones_arr = np.ones(5)
print('Vetor: ', repr(ones_arr))

Vetor:  array([1., 1., 1., 1., 1.])


In [54]:
# Fazendo a tranposta do vetor
transposed = np.transpose(ones_arr)
print('Tranposta: ', repr(transposed))

Tranposta:  array([1., 1., 1., 1., 1.])


#### Exercício 4

In [57]:
# Gerando o vetor
points = np.linspace(-3.5, 1.5, num = 101)
print('Vetor: ', repr(points))

Vetor:  array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,  0.5 ,
        0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,
        1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ])
