In [3]:
import numpy as np

## Analysis

In [4]:
# Criando a matriz
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

In [5]:
# Imprimindo o menor valor presente na matriz
print(arr.min())

-60


In [7]:
# Imprimindo o maior valor presente na matriz
print(arr.max())

72


In [8]:
print(repr(arr.min(axis=0)))

array([ -3,  -2, -60])


In [9]:
print(repr(arr.max(axis=-1)))

array([72,  3,  4])


## Statistical metrics

In [14]:
# Imprimindo a média
print(np.mean(arr))

2.0


In [15]:
# Imprimindo a variância
print(np.var(arr))

977.3333333333334


In [16]:
# Imprimindo a mediana
print(np.median(arr))

1.0


In [17]:
print(repr(np.median(arr, axis=-1)))

array([ 3.,  1., -2.])


## Time to Code!#


In [18]:
def get_min_max(data):
  overall_min = data.min()
  overall_max = data.max()
  return overall_min, overall_max

In [19]:
def col_min(data):
  min0 = data.min(axis=0)
  return min0

In [20]:
def basic_stats(data):
  mean = np.mean(data)
  median = np.median(data)
  var = np.var(data)
  return mean, median, var